"""'third'

Revision ID: 04884dea325b
Revises: c87cca87918d
Create Date: 2023-02-02 15:41:07.277480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04884dea325b'
down_revision = 'c87cca87918d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
